- name: Install Nginx
  host: WEB
  become: true
  task:
    - name: Install nginx
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: Start nginx
      ansible.builtin.systemd:
        name: nginx
        state: Started
        enabled: yes
